### ISSUE TITLE
multipart-post error

### ISSUE THREAD

**Issue by alex-roman** [cosmonawt/lua-telegram-bot#10]
Hi there,

I've got an error with example code and can't find the reason. Can you take a look please

```
lua: ...usr/local/share/lua/5.1/multipart/multipart-post.lua:57: unexpected type number
stack traceback:
    [C]: in function 'error'
    ...usr/local/share/lua/5.1/multipart/multipart-post.lua:57: in function 'encode'
    ./lua-bot-api.lua:94: in function 'makeRequest'
    ./lua-bot-api.lua:207: in function 'getUpdates'
    ./lua-bot-api.lua:1097: in function 'run'
    bot.lua:16: in main chunk
    [C]: ?
```

I have copied your example, add my token and place two files (JSON.lua and lua-bot-api.lua) in the same folder.

**Comment by ldb** [comment]
@prozacUa Are you sure you checked out the entire repo? Check wether you habe the file multipart/multipart-post.lua.
If not, use `git clone --recursive` instead of downloading the individual files.

**Comment by alex-roman** [comment]
@cosmonawt I have installed mulipart by `luarocks install multipart-post`. As you can see on an error listing the problem is in wrong format of variable passed to one of functions in multipart-post.lua.

**Comment by alirezamansori** [comment]
Takbar
