### ISSUE TITLE
what is error

### ISSUE THREAD

**Issue by ghost** [cosmonawt/lua-telegram-bot#12]
lua: ./lua-bot-api.lua:28: module 'JSON' not found:
    no field package.preload['JSON']
    no file '/usr/local/share/lua/5.2/JSON.lua'
    no file '/usr/local/share/lua/5.2/JSON/init.lua'
    no file '/usr/local/lib/lua/5.2/JSON.lua'
    no file '/usr/local/lib/lua/5.2/JSON/init.lua'
    no file '/usr/share/lua/5.2/JSON.lua'
    no file '/usr/share/lua/5.2/JSON/init.lua'
    no file './JSON.lua'
    no file '/usr/local/lib/lua/5.2/JSON.so'
    no file '/usr/lib/x86_64-linux-gnu/lua/5.2/JSON.so'
    no file '/usr/lib/lua/5.2/JSON.so'
    no file '/usr/local/lib/lua/5.2/loadall.so'
    no file './JSON.so'
stack traceback:
    [C]: in function 'require'
    ./lua-bot-api.lua:28: in main chunk
    [C]: in function 'require'
    lua-bot-api-test.lua:27: in main chunk
    [C]: in ?

**Comment by ldb** [comment]
You need to download and place `JSON.lua` in the bot directory, as I described [here](https://github.com/cosmonawt/lua-telegram-bot#installing).

**Comment by ghost** [comment]
thanks :+1:

**Comment by yurevich1** [comment]
To improve performance I would recommend to use any json library wrotten in pure C.
