### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by elisaado** [cosmonawt/lua-telegram-bot#23]
Hey, I wanted to ask this in the group you guys made, but I'm limited and it is a public group so I can't talk...

Here's my issue:

I like this wrapper/framework (let's use wrapper the next time) and I already built a bot with it, it's small, simple, made in lua, but there's something I miss, examples! I tried using `inlineKeyboards` but I couldn't find anything in the `README.md` and the only example there is, doesn't use the new functions.

Could you guys please provide examples?

That would be nice!
,
Eli | (@)enotly

**Comment by elisaado** [comment]
Great idea 👍

**Comment by ldb** [comment]
@elisaado Sorry, I don't plan on adding examples any time soon.
If you want, you can open a Pull Request and add some.

**Comment by elisaado** [comment]
@cosmonawt I was a bit younger when I opened this issue, I did not see the the bot-example.lua file.
