### ISSUE TITLE
How i can use it in windows

### ISSUE THREAD

**Issue by farhadhp** [cosmonawt/lua-telegram-bot#24]
How i can use it in windows ?

**Comment by i-Naji** [comment]
it's just a Lua Library...
I suggest you VM 😉

**Comment by yurevich1** [comment]
Just install lua into your Windows OS and use it.

**Comment by farhadhp** [comment]
Thanks,
I installed lua but not run this script!

**Comment by farhadhp** [comment]
`C:\Users\farhad\Downloads\Compressed\lua-telegram-bot-master\lua-telegram-bot-master
λ lua bot.lua
lua: bot.lua:27: module 'lua-bot-api' not found:
        no field package.preload['lua-bot-api']
        no file 'C:\Program Files (x86)\Lua\5.1\lua\lua-bot-api.luac'
        no file '.\lua-bot-api.dll'
        no file '.\lua-bot-api51.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\lua-bot-api.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\lua-bot-api51.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\clibs\lua-bot-api.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\clibs\lua-bot-api51.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\loadall.dll'
        no file 'C:\Program Files (x86)\Lua\5.1\clibs\loadall.dll'
stack traceback:
        [C]: in function 'require'
        bot.lua:27: in main chunk
        [C]: ?`

**Comment by ldb** [comment]
Everything has to be in the same directory.

**Comment by yurevich1** [comment]
The sciprt cannot find your lua-bot script. Where do you place your code and this lib?

**Comment by ldb** [comment]
> Everything has to be in the same directory.
